### PR TITLE
remove `collect_upstream_conda_tests` and `test_modified_upstream`

### PR DESCRIPTION
**Pull request by jaimergp**
### Description

Now that `conda/conda@main` has merged 23.10 back in, we can rely directly on conda's unaltered test suite. To be decided if we want to keep doing this, but for now let's just use it as is.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by jaimergp** [comment]
```
_______________________ test_install_features[libmamba] ________________________
[XPASS(strict)] Features not supported in libmamba
```

Did we accidentally fix something in `main`? 😱 Noice if true! This one was passing (i.e. failing as expected) in `conda/conda` 🤔

**Review by jezdez — APPROVED** [review]

**Comment by jaimergp** [comment]
Yep, I bisected through the recent history and that test started passing with 671b9c1bbb8d7c4d4e237cac17ad2cd3f5870aa1 being merged. I'll remove the `strict=True` upstream.

**Comment by jaimergp** [comment]
Submitted https://github.com/conda/conda/pull/13320 upstream.

**Comment by jaimergp** [comment]
`tests/test_misc.py::test_explicit_missing_cache_entries` fails on macOS because I assume the test order makes it have a PackageCache with an entry whose `url` is None. I added a patch in the same PR and will merge this one to unlock #365.

**Pull request merged**
