### PR TITLE
Fixing failing CI for windows

### LINKED ISSUE #296: `tests/test_activate.py::test_cmd_exe_basic_integration` errors due to missing `git`
The Upstream tests workflow failed on 2023-09-28 07:59 UTC

Full run: https://github.com/conda/conda-libmamba-solver/actions/runs/6335774958

(This post will be updated if another test fails, as long as this issue remains open.)

### PR DESCRIPTION
**Pull request by costrouc**
### Description

Closes #296 

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by costrouc** [comment]
Black commit to trigger CI and identify the windows issue

**Comment by costrouc** [comment]
First run all tests passed.

Second round

```shell
FAILED tests/cli/test_subcommands.py::test_env_update - assert not "Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /pkgs/r/win-64/repodata.json\n\nRetrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /pkgs/r/noarch/repodata.json\n\nRetrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /pkgs/main/noarch/repodata.json\n\nRetrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /pkgs/msys2/win-64/repodata.json\n\n"
```

Which does not address which this PR was opened for https://github.com/conda/conda-libmamba-solver/issues/296

**Comment by costrouc** [comment]
Now getting the following error

```
'.\dev\windows\itegration.bat' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by costrouc** [comment]
Still no luck reproducing :disappointed:

**Comment by costrouc** [comment]
This now failed 

```
FAILED ..\conda-libmamba-solver\tests\test_modified_upstream.py::test_conda_downgrade - AssertionError: assert '3.5.4' == '3.6.2'
```

Well if anything this is showing some tests that are flaky

**Comment by jaimergp** [comment]
If we can't reproduce it and the CI on `main` is not consistently showing this error, then it's a flaky test. It's due to timeouts in the shell response so it could be affected by the CI runtime and other variables we don't control. I'd suggest we close and only reopen if we observe it again.

**Comment by jaimergp** [comment]
> This now failed
> 
> ```
> FAILED ..\conda-libmamba-solver\tests\test_modified_upstream.py::test_conda_downgrade - AssertionError: assert '3.5.4' == '3.6.2'
> ```
> 
> Well if anything this is showing some tests that are flaky

This is an adjustment for [this upstream test](https://github.com/conda/conda/blob/9c7b2acbb9744d4673433197de6d34778585dbd0/tests/core/test_solve.py#L1161), which has not received any logic modifications (some formatting, but that's it). I'm concerned it only happened once, but I also see some decoding warnings, so maybe some bad IO got involved?

The main point of the test was to downgrade `conda`, and that happened successfully, so let's wait til it happens again.

Thanks for looking into it!

**Comment by costrouc** [comment]
Closing and will reopen a PR is occurs again.

**Pull request closed without merging**
