### PR TITLE
Ensure that channels match expected value in conda-build

### LINKED ISSUE #363: Conda build 3.27.1 fails with libmamba solver with key error then an assert error when key error corrected
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

This is a continuation of issue conda/conda-build#4991. After running the new version the same exception occured at conda/export.py, line 208
```
File "/home/<username>/.conda/envs/conda-23.9/lib/python3.11/site-packages/conda/exports.py", line 208, in display_actions
actions["LINK"] = [index[d] for d in actions["LINK"]]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/<username>/.conda/envs/conda-23.9/lib/python3.11/site-packages/conda/exports.py", line 208, in <listcomp>
actions["LINK"] = [index[d] for d in actions["LINK"]]
~~~~~^^^
KeyError: Dist(channel='https://<v4 url>/cbuild-test', dist_name='_libgcc_mutex-0.1-main', name='_libgcc_mutex', fmt='.tar.bz2', version='0.1', build_string='main', build_number=0, base_url=None, platform=None)
```

Per a recommendation line 208 in conda/exports.py was replaced locally with and tested:
`actions["LINK"] = [index.get(d, d) for d in actions["LINK"]]`

This seemed to address the `KeyError` but a new `AssertError` occurs:
```conda/plan.py, line 125, in display_actions
assert isinstance(prec, PackageRecord)
AssertionError
-----
conda info......
conda: 23.9.0
conda-build: 3.27.1.dev15
python version: 3.11.5.final.0
conda-libmamba-solver: 23.9.1
libmaba: 1.5.1```

The error was reconfirmed with the released version of 3.27.1.


### Conda Info

```shell
conda: 23.9.0
conda-build: 3.27.1.dev15
python version: 3.11.5.final.0
conda-libmamba-solver: 23.9.1
libmaba: 1.5.1
```

### Conda Config

```shell
See conda/conda-build#4991
```

### Conda list

```shell
See conda/conda-build#4991
```

### Additional Context

See conda/conda-build#4991

### PR DESCRIPTION
**Pull request by jaimergp**
### Description

Following up on https://github.com/conda/conda-build/pull/5037. Closes #363.

This issue is caused by a discrepancy in how each PackageRecord is built. `conda` will take `defaults` (a multichannel) as the "brand" channel for a PackageRecord, but `libmamba` takes the actual physical channel (e.g. `pkgs/main`) as the "brand" channel.

This is not an issue in `conda` itself because it uses a different mechanism to fetch the PackageRecords, but in `conda-build` it ends up raising a KeyError because of the channel identifier mismatch.

Let's see if mapping them for conda-build helps.

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by jaimergp** [comment]
Intriguing that `conda-libmamba-solver-src/tests/test_downstream.py::test_build_recipe[jedi]` fails in all platforms but Linux-conda-forge with:

```
WARNING: failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {MatchSpec("3.10.*==*_cp310"), MatchSpec("jedi==0.17.2=py310_1")}
Encountered problems while solving:
  - nothing provides python_abi 3.10.* *_cp310 needed by jedi-0.17.2-py310_1

Could not solve for environment specs
The following package could not be installed
└─ jedi 0.17.2.* py310_1 is not installable because it requires
   └─ python_abi 3.10.* *_cp310, which does not exist (perhaps a missing channel).
WARNING:conda_build.environ:failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {MatchSpec("3.10.*==*_cp310"), MatchSpec("jedi==0.17.2=py310_1")}
Encountered problems while solving:
  - nothing provides python_abi 3.10.* *_cp310 needed by jedi-0.17.2-py310_1

Could not solve for environment specs
The following package could not be installed
└─ jedi 0.17.2.* py310_1 is not installable because it requires
   └─ python_abi 3.10.* *_cp310, which does not exist (perhaps a missing channel).
```

Of course, it passes locally if run isolated. 

It's also intriguing that newly added test required three reruns to pass, consistently:

```
../conda-libmamba-solver-src/tests/test_channels.py::test_channel_matchspec PASSED [  1%]
../conda-libmamba-solver-src/tests/test_channels.py::test_channels_prefixdata PASSED [  2%]
../conda-libmamba-solver-src/tests/test_channels.py::test_channels_installed_unavailable PASSED [  3%]
../conda-libmamba-solver-src/tests/test_channels.py::test_mirrors_do_not_leak_channels[_setup_channels_alias] PASSED [  4%]
../conda-libmamba-solver-src/tests/test_channels.py::test_mirrors_do_not_leak_channels[_setup_channels_custom] PASSED [  5%]
../conda-libmamba-solver-src/tests/test_channels.py::test_jax_and_jaxlib PASSED [  6%]
../conda-libmamba-solver-src/tests/test_channels.py::test_encoding_file_paths PASSED [  7%]
../conda-libmamba-solver-src/tests/test_channels.py::test_conda_build_with_aliased_channels RERUN [  8%]  <<<
../conda-libmamba-solver-src/tests/test_channels.py::test_conda_build_with_aliased_channels RERUN [  8%]  <<<
../conda-libmamba-solver-src/tests/test_channels.py::test_conda_build_with_aliased_channels PASSED [  8%]  <<< HERE!
../conda-libmamba-solver-src/tests/test_downstream.py::test_build_recipe[baddeps] PASSED [  9%]
../conda-libmamba-solver-src/tests/test_downstream.py::test_build_recipe[jedi] RERUN [ 10%]
../conda-libmamba-solver-src/tests/test_downstream.py::test_build_recipe[jedi] RERUN [ 10%]
../conda-libmamba-solver-src/tests/test_downstream.py::test_build_recipe[jedi] RERUN [ 10%]
../conda-libmamba-solver-src/tests/test_downstream.py::test_build_recipe[jedi] FAILED [ 10%]
```

**Comment by jezdez** [comment]
pre-commit.ci autofix

**Review by jezdez — APPROVED** [review]

**Comment by jaimergp** [comment]
Errors (`test_conda_downgrade`) are known, and hopefully tamed by #378. So I'd say we merge :)

**Comment by desilinguist** [comment]
FYI, we use a local Artifactory instance to host our internal packages and a conda-forge cache, and we are still unable to build conda packages unless we set `CONDA_SOLVER=classic` when calling `conda build`. We get a KeyError with the mamba solver that looks like this:

<details><summary>Traceback</summary>

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/ec2-user/miniconda/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
      File "/home/ec2-user/miniconda/lib/python3.10/site-packages/conda/cli/main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
      File "/home/ec2-user/miniconda/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 170, in do_call
        result = plugin_subcommand.action(getattr(args, "_args", args))
      File "/home/ec2-user/miniconda/lib/python3.10/site-packages/conda_build/plugin.py", line 10, in build
        execute(*args, **kwargs)
      File "/home/ec2-user/miniconda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 572, in execute
        outputs = api.build(
      File "/home/ec2-user/miniconda/lib/python3.10/site-packages/conda_build/api.py", line 254, in build
        return build_tree(
      File "/home/ec2-user/miniconda/lib/python3.10/site-packages/conda_build/build.py", line 3808, in build_tree
        test(pkg, config=metadata.config.copy(), stats=stats)
      File "/home/ec2-user/miniconda/lib/python3.10/site-packages/conda_build/build.py", line 3551, in test
        environ.create_env(
      File "/home/ec2-user/miniconda/lib/python3.10/site-packages/conda_build/environ.py", line 1050, in create_env
        display_actions(actions, index)
      File "/home/ec2-user/miniconda/lib/python3.10/site-packages/conda/exports.py", line 214, in display_actions
        actions["LINK"] = [index[d] for d in actions["LINK"]]
      File "/home/ec2-user/miniconda/lib/python3.10/site-packages/conda/exports.py", line 214, in <listcomp>
        actions["LINK"] = [index[d] for d in actions["LINK"]]
    KeyError: Dist(channel='defaults', dist_name='jdk11-ac-11.0.18.10.1-0', name='jdk11-ac', fmt='.tar.bz2', version='11.0.18.10.1', build_string='0', build_number=0, base_url=None, platform=None)
   ```
   
   </details>
   
   This happens with:
   
   ```
   conda/23.11.0 requests/2.31.0 CPython/3.10.13 Linux/6.1.61-85.141.amzn2023.x86_64 amzn/2023 glibc/2.34 solver/libmamba conda-libmamba-solver/23.11.1 libmambapy/1.5.5
   ```

**Pull request merged**
