### PR TITLE
Do not use lockfiles in libmamba

### LINKED ISSUE #116: Error libmamba Could not open lockfile
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I looked at the [README.md](https://github.com/conda-incubator/conda-libmamba-solver) and didn't see anything to help

### What happened?

On our HPCC, conda is served via linux modules. Our sysadmins recently provided miniconda v 22.11.1-1 in a module similar to the many versions previously available. However, when creating a new conda environment with the new module loaded we get the following error:

The solver does seem to solve and the environment is created (if allowed), but it isn't clear what the consequences of the lockfile error are.

I tried putting `disable_lockfile: true` in .condarc and execute the environment creation using `MAMBA_DISABLE_LOCKFILE=TRUE conda create -n myenv` to see if that would eliminate the errors.  It didn't.

Is this something we can resolve without elevating user permissions on the module?

### Conda info

```Shell
active environment : base
    active env location : /share/apps/python/miniconda-py310_22.11.1-1
            shell level : 1
       user config file : /home/<userid>/.condarc
 populated config files : /home/<userid>/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.8.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.4=0
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /share/apps/python/miniconda-py310_22.11.1-1  (read only)
      conda av data dir : /share/apps/python/miniconda-py310_22.11.1-1/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /share/apps/python/miniconda-py310_22.11.1-1/pkgs
                          /home/<userid>/.conda/pkgs
       envs directories : /home/<userid>/.conda/envs
                          /share/apps/python/miniconda-py310_22.11.1-1/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.10.8 Linux/3.10.0-1160.66.1.el7.x86_64 centos/7.9.2009 glibc/2.17 solver/libmamba conda-libmamba-solver/22.8.1 libmambapy/1.0.0
                UID:GID : <UID>:<GID>
             netrc file : None
           offline mode : False
```

### Conda config

```Shell
==> /home/<userid>/.condarc <==
solver: libmamba
```

### Conda list

```Shell
# packages in environment at /share/apps/python/miniconda-py310_22.11.1-1:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
brotlipy                  0.7.0           py310h7f8727e_1002    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h5eee18b_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     22.11.1         py310hff52083_1    conda-forge
conda-content-trust       0.1.3           py310h06a4308_0    defaults
conda-libmamba-solver     22.12.0            pyhd8ed1ab_0    conda-forge
conda-package-handling    1.9.0           py310h5eee18b_1    defaults
cryptography              38.0.1          py310h9ce1e76_0    defaults
fmt                       8.1.1                h4bd325d_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      3.4             py310h06a4308_0    defaults
importlib-metadata        6.0.0              pyha770c72_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1    defaults
libarchive                3.6.1                hab531cd_0    defaults
libcurl                   7.87.0               h91b91d3_0    defaults
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h6a678d5_6    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libmamba                  1.0.0                ha06983f_0    defaults
libmambapy                1.0.0           py310ha06983f_0    defaults
libnghttp2                1.46.0               hce63b2e_0    defaults
libsolv                   0.7.22               he621ea3_0    defaults
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0               h1234567_1    defaults
libuuid                   1.41.5               h5eee18b_0    defaults
libxml2                   2.9.14               h74e7548_0    defaults
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
ncurses                   6.3                  h5eee18b_3    defaults
openssl                   1.1.1s               h7f8727e_0    defaults
pcre2                     10.37                h032f7d1_0    conda-forge
pip                       22.3.1          py310h06a4308_0    defaults
pluggy                    1.0.0           py310h06a4308_1    defaults
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.4           py310h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pysocks                   1.7.1           py310h06a4308_0    defaults
python                    3.10.8               h7a1cb2a_1    defaults
python_abi                3.10                    2_cp310    conda-forge
readline                  8.2                  h5eee18b_0    defaults
reproc                    14.2.4               h295c915_1    defaults
reproc-cpp                14.2.4               h295c915_1    defaults
requests                  2.28.1          py310h06a4308_0    defaults
ruamel.yaml               0.17.21         py310h5eee18b_0    defaults
ruamel.yaml.clib          0.2.6           py310h5eee18b_1    defaults
setuptools                65.5.0          py310h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.40.0               h5082296_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
toolz                     0.12.0          py310h06a4308_0    defaults
tqdm                      4.64.1          py310h06a4308_0    defaults
tzdata                    2022g                h04d1e81_0    defaults
urllib3                   1.26.13         py310h06a4308_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xz                        5.2.8                h5eee18b_0    defaults
yaml-cpp                  0.7.0                h27087fc_1    conda-forge
zipp                      3.11.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h5eee18b_0    defaults
zstd                      1.5.2                ha4553b6_0    defaults
```

### PR DESCRIPTION
**Pull request by jaimergp**
### Description

Closes #116

Needs https://github.com/mamba-org/mamba/pull/2256

Needs https://github.com/conda/conda-libmamba-solver/pull/151

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by costrouc** [comment]
Entire CI is failing see https://github.com/conda/conda-libmamba-solver/pull/151 so I'm having a hard time testing this. I also can't seem to reproduce the IndexSet error that I am seeing throughout the tests

**Comment by costrouc** [comment]
I just ran all of main tests again and same result which is expected from the previous PR being an exact match https://github.com/conda/conda-libmamba-solver/actions/runs/4354167911.

**Comment by costrouc** [comment]
Think this is related to https://github.com/conda/conda/pull/12453

**Comment by jaimergp** [comment]
macOS errors unrelated, and due to https://github.com/conda-forge/libxml2-feedstock/pull/90

**Comment by jaimergp** [comment]
We can retry in a bit once https://github.com/conda-forge/admin-requests/pull/694 kicks in.

**Comment by jaimergp** [comment]
Look at this, all green and shiny :) 
This is all ready for review. Just a temporary patch while we wait for #65 anyway, but in case that one doesn't make it, we have this stopgap.

ping @jezdez @costrouc

**Review by jezdez — APPROVED** [review]

**Pull request merged**
